# theme = "dark_plus"
theme = "dark_plus_and_status"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
# max-wrap = 25 # increase value to reduce forced mid-word wrapping
# max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

