theme = "dark_plus"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

