import = [
    # "~/.config/alacritty/themes/dark_plus.toml"
    # "~/.config/alacritty/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/dracula.toml"
]

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
# option_as_alt = "Both" # MacOs
opacity = 0.95
decorations = "None"
dynamic_padding = true
padding = { x = 8, y = 8 }

[colors]
transparent_background_colors = true

[shell]
program = "zsh"
