[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
# option_as_alt = "Both" # MacOs
opacity = 0.90
# decorations = "None"
dynamic_padding = true
padding = { x = 12, y = 12 }

[colors]
transparent_background_colors = true

[shell]
program = "zsh"
